name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build_on_win:
    runs-on: windows-2016
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run dist-windows
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/*.exe*
            ./dist/latest.yml
          fail_on_unmatched_files: true
          draft: true
