name: Trigger Docker Panda LB Update

on:
  workflow_dispatch:
  release:
    types: [published, unpublished]

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: beingenious/docker-panda-lb
          event-type: update-release-event
          client-payload: >-
            {
              "release_tag": "${{ github.event.inputs.release_tag || github.event.release.tag_name || '' }}",
              "repository": "${{ github.repository }}",
              "is_prerelease": ${{ github.event.inputs.is_prerelease || github.event.release.prerelease || false }}
            }
