name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
  CSC_LINK: ${{ secrets.CSC_LINK }}
  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
  WINDOWS_SIGN_TOKEN_ALIAS: ${{ secrets.WINDOWS_SIGN_TOKEN_ALIAS }}
  WINDOWS_SIGN_TOKEN_PASSWORD: ${{ secrets.WINDOWS_SIGN_TOKEN_PASSWORD }}
  BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}

jobs:
  build:
    # runs-on: macos-latest
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install xz rpm
      - run: npm install
      - run: npm run dist
